package org.apache.beam.testinfra.pipelines.apioveruse;

import java.lang.annotation.Annotation;
import java.util.UUID;
import org.apache.beam.sdk.options.Default;
import org.apache.beam.sdk.options.Default.InstanceFactory;
import org.apache.beam.sdk.options.DefaultValueFactory;
import org.apache.beam.sdk.options.Description;
import org.apache.beam.sdk.options.PipelineOptions;
import org.apache.beam.sdk.options.Validation.Required;
import org.checkerframework.checker.initialization.qual.Initialized;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;
import org.checkerframework.checker.nullness.qual.UnknownKeyFor;

public interface QuotaOptions extends PipelineOptions {
  @Description("The Quota API service host i.e. localhost:8080")
  @Required
  String getQuotaServiceAddress();
  void setQuotaServiceAddress(String value);

  @Description("The ID to identify a quota allocation; autogenerated as a UUID if not provided")
  @Default.InstanceFactory(QuotaIdDefaultValueFactory.class)
  String getQuotaId();
  void setQuotaId(String value);

  class QuotaIdDefaultValueFactory implements DefaultValueFactory<String> {
    @Override
    public String create(PipelineOptions ignored) {
      return UUID.randomUUID().toString();
    }
  }

  @Description("The Quota refresh interval in milliseconds")
  @Required
  Long getQuotaRefreshIntervalMilliseconds();
  void setQuotaRefreshIntervalMilliseconds(Long value);

  @Description("The Quota size")
  @Required
  Long getQuotaSize();
  void setQuotaSize(Long value);
}
