###############################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

ARG BASE
# py_version is the Python version to install; expected: major.minor.patch:
ARG py_version
ARG alpine_version=3.21
ARG TAG=${py_version}-alpine${alpine_version}
FROM ${BASE} AS base
LABEL Author="Apache Beam <dev@beam.apache.org>"

FROM python:${TAG} AS final

#COPY sdks/python/container/py310/build/target/base_image_requirements.txt /tmp/base_image_requirements.txt
# Contains the boot entrypoint and related files such as licenses.
COPY --from=base /opt /opt

ENV CLOUDSDK_CORE_DISABLE_PROMPTS yes

RUN apk add build-base && \
    apk add bzip2-dev && \
    apk add ccache && \
    apk add gcc && \
    apk add linux-headers && \
    apk add lz4-dev && \
    apk add openssl-dev && \
    apk add cython && \
    apk add zlib-dev

RUN pip install --upgrade pip setuptools wheel

RUN \
    apk add geos-dev && \
    apk add git && \
    pip install cython && \
    pip install geos && \
    pip install numpy && \
    git clone https://github.com/shapely/shapely.git && \
    cd shapely && \
    python setup.py install

RUN \
   apk add cmake && \
   apk add libarrow && \
   apk add apache-arrow-dev && \
   git clone https://github.com/apache/arrow.git && \
   cd arrow/python && \
   python setup.py install

RUN pip install apache_beam[gcp]

RUN \
    # Install Google Cloud SDK.
    mkdir -p /usr/local/gcloud && \
    cd /usr/local/gcloud && \
    curl -s -O https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz && \
    tar -xf google-cloud-sdk.tar.gz && \
    /usr/local/gcloud/google-cloud-sdk/install.sh && \
    rm -rf /usr/local/gcloud/google-cloud-sdk/.install/.backup && \
    rm google-cloud-sdk.tar.gz

RUN \
    # Configure ccache prior to installing Beam SDK. This speeds up wheels compilation when installing the SDK from sources.
    ln -s /usr/bin/ccache /usr/local/bin/gcc && \
    # These parameters are needed as pip compiles artifacts in random temporary directories.
    ccache --set-config=sloppiness=file_macro && ccache --set-config=hash_dir=false && \
    pip freeze --all && \
    # Remove pip cache.
    rm -rf /root/.cache/pip

ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin
ENV PATH $PATH:/usr/local/bin
ENV LANG=C.UTF8

ENTRYPOINT ["/opt/apache/beam/boot"]
