ARG SDK
FROM ubuntu:noble AS base
# py_version is the Python version to install; expected: major.minor.patch:
ARG py_version

ENV DEBIAN_FRONTEND noninteractive

RUN \
    apt update && \
    apt install -y \
    ca-certificates \
    build-essential \
    libssl-dev \
    openssl \
    wget \
    zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

RUN \
    wget https://www.python.org/ftp/python/${py_version}/Python-${py_version}.tgz && \
    tar -xvf Python-${py_version}.tgz && \
    cd Python-${py_version} && \
    ./configure && \
    make && \
    make install

FROM ${SDK} as launcher
FROM base AS beam

RUN pip3 install apache-beam[gcp]

COPY --from=launcher /opt /opt

ENTRYPOINT ["/opt/apache/beam/boot"]
